//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinpointOnenote.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PinpointOnenote.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;StylingBank&gt;
        ///  &lt;BaseStyles name=&quot;Base&quot;&gt;&lt;!-- Things that never change --&gt;
        ///    &lt;SectionTabCol&gt;#F6B078&lt;/SectionTabCol&gt;
        ///    &lt;Font&gt;Calibri&lt;/Font&gt;
        ///    &lt;SpaceBefore&gt;0.0&lt;/SpaceBefore&gt;
        ///    &lt;SpaceAfter&gt;0.0&lt;/SpaceAfter&gt;
        ///    &lt;TwoFactorTrue&gt;#2AD00E&lt;/TwoFactorTrue&gt;
        ///    &lt;TwoFactorFalse&gt;#FF8181&lt;/TwoFactorFalse&gt;
        ///  &lt;/BaseStyles&gt;
        ///  &lt;TableSizings&gt;
        ///    &lt;!-- Font weights for table titles are given as CSS style properties in the CDATA value --&gt;
        ///    &lt;TableSizing name=&quot;Small&quot; def [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OneNotePageAndElementStyles {
            get {
                return ResourceManager.GetString("OneNotePageAndElementStyles", resourceCulture);
            }
        }
    }
}
